### ISSUE TITLE
Not mark all variables as secrets

### ISSUE THREAD

**Issue by laptevn** [dkershner6/aws-ssm-getparameters-action#42]
Hi there,
I finally found the action that hides variables as secrets :-)
But it does too much and hides all variables.

This leads to situations when lots of useful information is masked in actions log because they depend on non-secret variables that this action marked as secrets.

What if https://github.com/dkershner6/aws-ssm-getparameters-action/blob/main/src/process.ts#L68 line will be executed only if `withDecryption` is set to true?

**Comment by laptevn** [comment]
This PR https://github.com/dkershner6/aws-ssm-getparameters-action/pull/43 should solve this issue

**Comment by dkershner6** [comment]
Thank you!
